### ISSUE TITLE
bot doesn't listen to discord users that are streaming video

### ISSUE THREAD

**Issue by robled** [jeremycline/btfm#15]
steps to reproduce:

1.  stream video
2.  bot doesn't listen, ever

**Comment by jeremycline** [comment]
Hello @robled, thank you for your bug report.

I can assure you we have top folks working on it.

**Comment by robled** [comment]
Who?

**Comment by bowlofeggs** [comment]
Top. Men.

**Comment by jeremycline** [comment]
This is now resolved with the latest version of Serenity for your entertainments international
